services:
  # MySQL 데이터베이스 설정
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: lineup_db
      MYSQL_ROOT_PASSWORD: et1234!!
      MYSQL_USER: root
      MYSQL_PASSWORD: et1234!!
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  # 스프링 부트 애플리케이션 설정
  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # DB 연결 정보 (서비스 이름인 'db'로 접근)
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/lineup_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: et1234!!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update