name: CI/CD - Git Pull and Docker Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          script: |
            cd ~/line-up-be
            # 서버 상태 강제 초기화 (pull 에러 방지)
            git fetch --all
            git reset --hard origin/main
            
            # 빌드 캐시 없이 새로 빌드 (build 명령어에 --no-cache 사용)
            docker-compose build --no-cache
            docker-compose up -d
            
            docker image prune -f