name: CI/CD - Git Pull and Docker Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          script: |
            cd ~/line-up-be
            # 1. 최신 코드 가져오기
            git pull origin main
            
            # 2. 도커 컨테이너 중지 및 새 이미지 빌드/실행
            # --build 옵션이 서버에서 Dockerfile의 빌드 단계를 실행합니다.
            docker-compose down
            docker-compose up -d --build --no-cache
            
            # 3. 미사용 이미지 정리
            docker image prune -f